### ISSUE TITLE
Ping issue is still a problem

### ISSUE THREAD

**Issue by NathanDontGotDis** [Trojaner25/Rocket-Regions#70]
I have updated the framecount in the config and the ping only drops about 2-5 per 10 frames I set, So is there anyway to improve that in the coding of regions or possible ways to reduce in config? Like maybe more configurable options.

**Comment by jserodio** [comment]
I had ping spikes but that's is because this plugin throws a lot of errors on the console. Even if you use the command /EnterEffect with a known value it becomes even more unstable. With the plugin activated my server has +200 ping, with the plugin disabled no errors in console and 30ms of ping. It's a fact.

**Comment by SolarSupremacy** [comment]
I believe we have a similar issue.

CEO @ SGN

**Comment by Trojaner** [comment]
A temprorary fix for the errors is to remove any Enter- and LeaveEffects from the config.

**Comment by Trojaner** [comment]
Should be fixed with latest updates
